name: check-npm-token

env:
  FORCE_COLOR: 2
  NODE: 14

on:
  push:
    branches:
      - check-npm-token

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE }}
      - run: printf "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - run: npm whoami
